name: 'Install Doppler CLI'
description: 'Install the Doppler CLI into your PATH'
branding:
  icon: 'download'
  color: 'blue'
runs:
  pre: chainguard-phonehome.js
  using: 'node24'
  main: 'bin/index.js'

